# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun May 18 05:01:52 2025
# ------------------------------------------------

package:
  name: numpy
  version: 2.2.6
source:
  - sha256: 4d7604ff87ace3af216f4ff469ce101315fc0a8c3f8b38fb721c5299d7b87406
    url: https://github.com/numpy/numpy/archive/refs/tags/v2.2.6.tar.gz
  - folder: numpy/_core/src/highway
    git_rev: 0b696633f9ad89497dd5532b55eaa01625ad71ca
    git_url: https://github.com/google/highway.git
  - folder: numpy/_core/src/common/pythoncapi-compat
    git_rev: 0f1d42a10a3f594ad48894912396df31b2c2d55d
    git_url: https://github.com/python/pythoncapi-compat.git
  - folder: numpy/_core/src/npysort/x86-simd-sort
    git_rev: 9a1b616d5cd4eaf49f7664fb86ccc1d18bad2b8d
    git_url: https://github.com/intel/x86-simd-sort.git
  - folder: numpy/_core/src/umath/svml
    git_rev: 32bf2a98420762a63ab418aaa0a7d6e17eb9627a
    git_url: https://github.com/numpy/SVML.git
  - folder: numpy/fft/pocketfft
    git_rev: 33ae5dc94c9cdc7f1c78346504a85de87cadaa12
    git_url: https://github.com/mreineck/pocketfft.git
  - folder: vendored-meson/meson
    git_rev: 0d93515fb826440d19707eee47fd92655fe2f166
    git_url: https://github.com/numpy/meson.git
build:
  entry_points:
    - f2py = numpy.f2py.f2py2e:main
    - numpy-config = numpy._configtool:main
  number: '0'
  run_exports:
    - numpy >=1.21,<3
  string: py310h4987827_0
requirements:
  build:
    - vs2019_win-64 19.29.30139 h7dcff83_26
    - vs_win-64 2019.11 h7dcff83_26
    - vswhere 3.1.7 h40126e0_1
  host:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2025.4.26 h4c7d964_0
    - colorama 0.4.6 pyhd8ed1ab_1
    - cython 3.1.0 py310h6bd2d47_1
    - importlib-metadata 8.6.1 pyha770c72_0
    - libblas 3.9.0 12_h7532347_netlib
    - libcblas 3.9.0 12_hb3dda5d_netlib
    - libexpat 2.7.0 he0c23c2_0
    - libffi 3.4.6 h537db12_1
    - libglib 2.84.1 hbc94333_1
    - libiconv 1.18 h135ad9c_1
    - libintl 0.22.5 h5728263_3
    - liblapack 3.9.0 12_h13b7882_netlib
    - liblzma 5.8.1 h2466b09_1
    - libsqlite 3.49.2 h67fdade_0
    - libzlib 1.3.1 h2466b09_2
    - meson 1.8.0 pyh29332c3_0
    - meson-python 0.18.0 pyh70fd9c4_0
    - ninja 1.12.1 hc790b64_1
    - openssl 3.5.0 ha4e3fda_1
    - packaging 25.0 pyh29332c3_1
    - pcre2 10.45 h99c9b8b_0
    - pip 25.1.1 pyh8b19718_0
    - pkg-config 0.29.2 h88c491f_1009
    - pyproject-metadata 0.9.1 pyhd8ed1ab_0
    - pyproject_hooks 1.2.0 pyhd8ed1ab_1
    - python 3.10.17 h8c5b53a_0_cpython
    - python-build 1.2.2.post1 pyhff2d567_1
    - python_abi 3.10 7_cp310
    - setuptools 80.1.0 pyhff2d567_0
    - tk 8.6.13 h5226925_1
    - tomli 2.2.1 pyhd8ed1ab_1
    - tzdata 2025b h78e105d_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h2b53caa_26
    - vc14_runtime 14.42.34438 hfd919c2_26
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.21.0 pyhd8ed1ab_1
  run:
    - libblas >=3.9.0,<4.0a0
    - libcblas >=3.9.0,<4.0a0
    - liblapack >=3.9.0,<4.0a0
    - python >=3.10,<3.11.0a0
    - python_abi 3.10.* *_cp310
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
  run_constrained:
    - numpy-base <0a0
test:
  commands:
    - f2py -h
    - python -c "import numpy, sys; sys.exit(not numpy.test(verbose=1, label='full',
      tests=None, extra_argv=['-k', 'not (_not_a_real_test)', '-nauto', '--timeout=3000',
      '--durations=50', '--maxfail=100']))"
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core.numeric
    - numpy.core.umath
    - numpy.ctypeslib
    - numpy.distutils
    - numpy.dtypes
    - numpy.exceptions
    - numpy.f2py
    - numpy.fft
    - numpy.lib
    - numpy.lib.array_utils
    - numpy.lib.format
    - numpy.lib.introspect
    - numpy.lib.mixins
    - numpy.lib.npyio
    - numpy.lib.recfunctions
    - numpy.lib.scimath
    - numpy.lib.stride_tricks
    - numpy.linalg
    - numpy.linalg.lapack_lite
    - numpy.ma
    - numpy.ma.extras
    - numpy.ma.mrecords
    - numpy.polynomial
    - numpy.polynomial.chebyshev
    - numpy.polynomial.hermite
    - numpy.polynomial.hermite_e
    - numpy.polynomial.laguerre
    - numpy.polynomial.legendre
    - numpy.polynomial.polynomial
    - numpy.random
    - numpy.random.mtrand
    - numpy.testing
    - numpy.testing.overrides
    - numpy.typing
    - numpy.typing.mypy_plugin
    - numpy.version
  requires:
    - cython
    - hypothesis
    - meson
    - pkg-config
    - pytest
    - pytest-timeout
    - pytest-xdist
    - pytz
    - setuptools <60.0.0
    - typing_extensions
about:
  dev_url: https://github.com/numpy/numpy
  doc_url: https://numpy.org/doc/stable/
  home: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250518.1.1
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
    - xhochy
  remote_url: https://github.com/conda-forge/numpy-feedstock
  sha: 11064489b53a6cc29eab6793ea9fa881de34cf69
