defects_data_dir: data/defects4codellm-main/data
website_data_dir: data/defects4codellm-main/website/src/data
humaneval_jsonl_path: data/human-eval-master/data/HumanEval.jsonl/human-eval-v2-20210705.jsonl
output_root: work_dirs
run_name: 20260302_154707_feature_extraction
seed: 42
models: StarCoder
encoding: utf-8
